### ISSUE TITLE
Spoofing is not necessary anymore

### ISSUE THREAD

**Issue by gitdreamlteui** [yahgoo/Hackintosh-HP-840-G3-Opencore-Ventura#1]

**Comment by yahgoo** [comment]
I dont get it. How can OCLP be much better when i have to install OCLP? I think OCLP still have to spoof to HD630 in order for it to work

**Comment by biertester** [comment]
Apparently not, there’s no graphical glitch at all with OCLP so apparently they in some sort optimized old graphics kext to ventura

**Comment by yahgoo** [comment]
There is no graphical glitch on 840 G3 with the latest WEG kext. I got it clean installed with Ventura before OCLP is officially released to support Ventura. Moreover, OC team only support OCLP used on non-supported mac. I know what/how works on a hackintosh laptop without OCLP.
