### ISSUE TITLE
Showing Prohibitory Symbol.

### ISSUE THREAD

**Issue by Lost-Entrepreneur439** [yahgoo/Hackintosh-HP-840-G3-Opencore-Ventura#2]
I wanted to upgrade my 840 G3 to Ventura (it's currently on Monterey), so I put this EFI on my USB drive and booted to it first to test (and also because i have no idea how to upgrade), and when I boot it, I just get the prohibitory symbol.

**Comment by yahgoo** [comment]
Try another usb port to boot. See [[Solved] Hackintosh prohibited sign when trying to setup](https://www.tonymacx86.com/threads/solved-hackintosh-prohibited-sign-when-trying-to-setup.258548/)

**Comment by EhshanAmin** [comment]
Wifi is not working properly as it won't search for wifi networks... Some times it shows somehow...
And there are some graphical glitchs while playing videos on browser and when switching to 2nd desktop space...

**Comment by Lost-Entrepreneur439** [comment]
> Try another usb port to boot. See [[Solved] Hackintosh prohibited sign when trying to setup](https://www.tonymacx86.com/threads/solved-hackintosh-prohibited-sign-when-trying-to-setup.258548/)

Tried both USB ports, neither worked.

**Comment by ridoamali** [comment]
can you fix the rtc power loss after restart ?

**Comment by yahgoo** [comment]
Just press enter to reboot on RTC power loss. Anyway, it does not occur frequently.
