### ISSUE TITLE
Wifi+Bluetooth+igpu

### ISSUE THREAD

**Issue by EhshanAmin** [yahgoo/Hackintosh-HP-840-G3-Opencore-Ventura#3]
Works well with itlwm+heliport. Bluetooth is bit of buggy.
But the main issue is graphical glitchs...
Its like blinking everything 10-20 second while playing videos on VLC as well as browsers...
Can you please help me with that.

**Comment by EhshanAmin** [comment]
Don't you have any solution to those issues..???

**Comment by yahgoo** [comment]
Will u help someone who said "Don't you have any solution to those issues..???"
