### ISSUE TITLE
Changes If you can

### ISSUE THREAD

**Issue by scorpionTaj** [yahgoo/Hackintosh-HP-840-G3-Opencore-Ventura#4]
pls Can you add intel Wifi / Bluetooth Native support to A modified Version of your EFI ?

**Comment by yahgoo** [comment]
Airportitlwm alpha is still buggy. For my other laptop, I installed itlwm.kext. Enable in config.plist.
Run it with HeliPort. 
Download [itlwm](https://github.com/OpenIntelWireless/itlwm/releases)
and [HeliPort](https://github.com/OpenIntelWireless/HeliPort/releases)
Autorun HeliPort by adding it into login item in Ventura Settings
Give this a shot.
Share your EFI if it works

**Comment by scorpionTaj** [comment]
I have a preconfigured EFI for my Device but it work just for Montery if you want it :
https://drive.google.com/file/d/1yrb57oHux84UM0KH0-tV3Xdh2ntUlGHz/view

**Comment by yahgoo** [comment]
Thanks
